
services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code

  frontend:
    build:
      context: ./frontend
      target: dev                     # Use the dev stage of the Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/code
    profiles:
      - dev
    command: ["npm", "run", "start"]
    stdin_open: true
    tty: true
